# Generated by Django 2.0.5 on 2018-06-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete='DO_NOTHING', to='blog.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
        migrations.AddField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='blog.ArticleTag', to='blog.Tag'),
        ),
    ]
